# Generated by Django 5.0.3 on 2024-04-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='id_cardapio',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_user',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
