# Generated by Django 5.0.3 on 2024-04-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cardapio_id_cardapio_alter_usuarios_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='id_cardapio',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_user',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
