# Generated by Django 5.0.3 on 2024-04-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cardapio_id_cardapio_alter_usuarios_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='id_user',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='id_usuarios',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='id_cardapio',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='ingredientes',
            field=models.TextField(),
        ),
    ]
