# Generated by Django 5.0.3 on 2024-04-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cardapio_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='id_cardapio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='id_usuarios',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
